#!/system/bin/sh
hos="/sdcard/ba"
whk="$hos/wiki"
err="echo Error!"
fgx="============"
inc="echo Input number or command:"
[ -e "$hos/" ]&&echo 'Welecome to use MaWiki&BBS'||{
echo Installing...
mkdir -p "$hos/main" "$hos/user" "$whk"
touch "$hos/ai"
echo Master name:SYSOP
echo New password:
read mnp
smk="$hos/user/SYSOP"
mkdir -p "$smk/diary" "$smk/mail"
echo "$mnp">>$smk/pwd
}
wblg(){
clear
echo Login:
read ua
echo Password:
read pa
[ "$ua" = "" ]&&np=0||{
[ -e "$hos/user/$ua" ]&&np="`cat "$hos/user/$ua/pwd"`ck"
}
[ "${pa}ck" == "$np" ]&&{
na="$ua"
usv="$hos/user/$na"
}||{
$err
echo Join us?[Y/N]:
read ju
case $ju in
Y|y)
echo Please input your name:
read nep
echo Please input new password:
read npd
chk="`ls "$hos/user" | grep "$nep"`"
[ "$chk" == "$nep" -o "$nep" = "" ]||{
echo Please input verifcation code:
vv="`cat /proc/sys/kernel/random/uuid`"
vv="${vv%%-*}"
echo $vv
read vc
[ "$vc" == "$vv" ]&&{
usk="$hos/user/$nep"
mkdir -p "$usk/diary" "$usk/mail"
echo $npd>>$usk/pwd
na="$nep"
usv="$hos/user/$na"
}
}
;;
esac
}
}
fid(){
while true
do
clear
cat "$rmk"
echo Press enter to back
[ "$na" == "guest" ]&&{
read nul
break 1
}||{
echo Input e to insert a new paragraph
echo Input c to continue write
read pd
case $pd in
e)
clear
echo Input title:
read tt
echo Word:
read nwd
echo >>$rmk
echo $tt >>$rmk
echo -------- >>$rmk
echo $nwd >>$rmk
;;
c)
echo Word:
read nw 
echo $nw >>$rmk
;;
*)
break 1
;;
esac
}
done
}
zxth(){
while true
do
clear
cat "$wbb"
echo 'Input reply(Input e go back):'
read ry
if [ "$ry" == "e" ]
then
break 1
elif [ "$ry" == "" ]
then
echo refreshing... 
else
[ "$na" == "guest" ]&&wblg||{
echo $na  `date` >>$wbb
echo $ry >>$wbb
echo >>$wbb
}
fi
done
}
pxcx(){
while read nr
do
co=$(($co+1))
[ "$sel" -le "$co" -a "$(($sel+10))" -ge "$co" ]&&echo $co.$nr
done
}
chse(){
[ "$na" == "guest" ]&&wblg||{
vck="`cat "$wbb/opt/$1" | grep "$na"`"
[ "$na" == "$vck" ]||{
echo $na >> "$wbb/opt/$1"
clear
cat "$wbb/opt/$1"
echo selected it.
sleep 3
}
}
}
pdg(){
wbn=""
co="0" 
ls "$1"|while read nr
do
co=$(($co+1))
[ "$int" == "$co" ]&&echo "$nr"
done
}
cc(){
for lop in `ls "$wbb/opt/"`
do
echo $lop.$1 \(`cat "$wbb/opt/$lop" | wc -l`\)
shift
done
}
na="guest"
sleep 1
while true
do
clear
echo MaWiki  User:$na
echo Total entry:`ls "$whk" | wc -l`
echo $fgx
echo 1.Search
echo 2.Exit
echo 3.Go to MaBBS
echo 4.Random
[ "$na" == "guest" ]&&echo 5.Login||{
echo 5.Make a new entry
echo 6.Diary 
echo 7.Reset your password
}
echo Input command:
read cmd
case $cmd in
1)
clear
echo Input Keyword or tags:
read kw
[ "$kw" == "" ]||{
clear
echo Result
echo $fgx
ls "$whk" | grep "$kw" | while read jg
do
echo ${jg%%+*}
done
echo Which one:
read mtt
[ "$mtt" == "" ]||{
tkw=`ls "$whk" | grep "$mtt"`
[ "$tkw" == "" ]||{
[ -e "$whk/$tkw" ]&&{
rmk="$whk/$tkw"
fid
}
}
}
}
;;
2)
echo Bye
break
;;
3)
while true
do
clear
echo Welecome,$na
date
[ -e "$hos/bul" ]&&echo Bulletin:`cat "$hos/bul"`
echo $fgx
co=0
ls "$hos/main" | while read bm
do
co=$(($co+1))
echo $co.$bm \(`ls "$hos/main/$bm/" | wc -l `\)
done
echo $fgx
echo a.Mail box
echo b.Back to MaWiki
[ "$na" == "SYSOP" ]&&{
echo c.Make a part
echo d.Delete a part
echo e.Release bulletin
}
$inc
read pac
[ "$pac" == "" ]&&pac="#"
case $pac in
a)
[ "$na" == "guest" ]&&wblg||{
sel=0
while true
do
clear
echo Mail box
echo $fgx
co="0"
ls "$usv/mail" | pxcx
echo $fgx
echo a.Send mail
echo b.Back
[ `ls "$usv/mail" | wc -l ` -ge 10 ]&&echo c.Next page
$inc
read int
case $int in
a)
clear
echo From:$na
echo To:
read st
[ "$st" == "" ]||{
[ "$st" == "AI" ]&&
{
echo Word:
read swd
[ "$swd" == "study" ]&&{
echo You say:
read ys
echo AI say:
read as
echo $ys-$as >>${hos}/ai
}
ais="`grep "$swd" "$hos/ai"`"
ais=${ais#*-}
[ "$swd" == "" -o "$ais" == "" ]&&ais="Sorry,I dont know what do you say"
echo Talk AI >>$usv/mail/Talk_AI
date >>$usv/mail/Talk_AI
echo $ais >>$usv/mail/Talk_AI
echo >>$usv/mail/Talk_AI
}
[ -e "$hos/user/$st" ]&&{
echo $fgx
echo Title:
read swd
isw="$hos/user/$st/mail/$swd"
[ "$swd" == "" -o -e "$isw" ]||{
echo Word:
read iwd
echo From:$na>>$isw
echo To:$st>>$isw
date>>$isw
echo $fgx>>$isw
echo $iwd >>$isw
echo OK!
}
}
}
sleep 1
;;
b)
break 1
;;
c)
[ `ls "$usv/mail" | wc -l` -ge 10 ]&&sel="$(($sel+10))"
;;
*)
clear
wbn="`pdg "$usv/mail"`"
[ "$wbn" == "" ]||{
cat "$usv/mail/$wbn"
echo Press enter to back
echo Input d to delete
read nul
[ "$nul" == "d" ]&&rm -rf "$usv/mail/$wbn"
}
;;
esac
done
}
;; 
b)
break
;;
c)
clear
[ "$na" == "SYSOP" ]&&{
echo New part name:
read npn
mkdir "$hos/main/$npn"
}
;;
d)
[ "$na" == "SYSOP" ]&&{
echo Which part to delete:
read dpw
rm -rf "$hos/main/$dpw"
}
;;
e)
[ "$na" == "SYSOP" ]&&{
clear
echo Input bulletin:
read bul
echo "$bul" > $hos/bul
}
;;
*)
int="$pac"
pac="`pdg "$hos/main"`"
[ "$pac" == "" ]||{
sel="0"
while true
do
pcz="$hos/main/$pac"
clear
echo Welecome,$na   Part:$pac
echo $fgx
co="0"
ls "$pcz" | pxcx
echo $fgx
echo a.Make a new post
echo b.Back
[ `ls "$pcz" | wc -l ` -ge 10 ]&&echo c.Next page
[ "$na" == "SYSOP" ]&&echo d.Delete a post
$inc
read int
case $int in
a)
[ "$na" == "guest" ]&&wblg||{
clear
echo 'This is a [1.Post 2.Vote]:'
read cht
case $cht in
1)
clear
echo Input the title:
read tit
[ "`ls "$pcz" | grep "$tit"`" == "" ]&&{
echo Word:
read wod
stt="$pcz/$tit"
echo $tit >>$stt
echo $fgx >>$stt
echo Post master:$na  `date` >>$stt
echo $wod >>$stt
echo >>$stt
}
;;
2)
clear
echo Input the title:
read tit
[ "`ls "$pcz" | grep "$tit"`" == "" ]&&{
echo Main word:
read wod
echo "Option head:"
read oph
echo "Option:"
read opt
echo 'Use talking?[Y/N]:'
read utk
tsm="$pcz/$tit"
mkdir "$tsm"
echo $tit >>$tsm/main
echo $fgx >>$tsm/main
echo Vote master:$na  `date` >>$tsm/main
echo $wod >>$tsm/main
echo $opt>>$tsm/data
mkdir "$tsm/opt" 
for sle in $oph
do
touch "$tsm/opt/$sle"
done
[ "$utk" == "y" ]&&{
echo Talk>>"$tsm/talk"
echo $fgx >>"$tsm/talk"
}
}
;; 
esac
}
;;
b)
break 1
;;
c)
[ `ls "$pcz" | wc -l ` -ge 10 ]&&sel="$(($sel+10))"
;;
d)
[ "$na" == "SYSOP" ]&&{
echo Which post delete:
read tdw
rm -rf "$pcz/$tdw"
}
;;
*)
wbn="`pdg "$pcz"`"
[ "$wbn" == "" ]||{
wbb="$pcz/$wbn"
[ -f "$wbb" ]&&zxth||{
clear
cat "$wbb/main"
echo $fgx
cc `cat "$wbb/data"`
[ -e "$wbb/talk" ]&&echo Input t to talk,or
echo 'Choose one:'
read ry
[ "$ry" == "" ]||{
[ "$ry" == "t" ]&&{
[ -e "$wbb/talk" ]&&{
wbb="$wbb/talk"
zxth
}
}||{
[ -e "$wbb/opt/$ry" ]&&chse $ry
}
}
}
}
;;
esac
done
}
;;
esac
done
;;
5)
[ "$na" == "guest" ]&&wblg||{
clear
echo Input Main title:
read mt
[ "`ls "$whk" | grep "$mt"`" == "" ]&&{
echo Tags:
read tgs
echo Word:
read wd
mwt="$whk/$mt+$tgs"
echo $mt>>$mwt
echo Made by:$na `date`>>$mwt
echo Tags:$tgs>>$mwt
echo $fgx >>$mwt
echo $wd >>$mwt
rmk="$whk/$mt+$tgs"
fid
}
}
;;
4)
jld="`ls "$whk" | wc -l`"
[ "$jld" == "0" ]&&{
echo Not found...
sleep 1
}||{
int=$((`date +%s`%$jld+1))
rmk="$whk/`pdg "$whk"`"
fid
}
;;
6)
[ "$na" == "guest" ]&&wblg||{
cfd="$usv/diary"
sel="0"
while true
do
clear
echo Welecome,$na
echo $fgx
co="0"
ls "$cfd" | pxcx
echo $fgx
echo a.Write diary
echo b.Back
[ `ls "$cfd" | wc -l ` -ge 10 ]&&echo c.Next page
$inc
read int
case $int in
a)
clear
mt="`date +%y.%m.%d`"
[ "`ls "$cfd" | grep "$mt"`" == "" ]&&{
echo Word:
read wd
mwt="$cfd/$mt"
echo Diary:$mt>>$mwt
echo $wd >>$mwt
}
rmk="$cfd/$mt"
fid
;;
b)
break 1
;;
c)
[ `ls "$cfd" | wc -l ` -ge 10 ]&&sel="$(($sel+10))"
;;
*)
wbn="`pdg "$cfd"`"
[ "$wbn" == "" ]||{
rmk="$cfd/$wbn"
fid
}
;;
esac
done
}
;;
7)
[ "$na" == "guest" ]&&wblg||{
clear
echo Input your new password:
read nrd
[ "$nrd" == "" ]||echo $nrd>$usv/pwd
}
;;
esac
done