#!/system/bin/sh
hos="/sdcard/ba"
whk="$hos/wiki"
err="echo Error!"
if [ -e "$hos/" ]
then
echo 'Welecome to use MaWiki&BBS'
else
echo Installing...
mkdir "$hos/"
mkdir -p "$hos/main" "$hos/user" "$whk"
touch "$hos/ai"
echo Master name:SYSOP
echo New password:
read mnp
smk="$hos/user/SYSOP"
mkdir "$smk"
mkdir "$smk/diary"
echo "$mnp">>$smk/pwd
fi
wblg(){
clear
echo Login:
read ua
echo Password:
read pa
if [ "$ua" = "" ]
then
np=0
else
if [ -e "$hos/user/$ua" ]
then
np="`cat "$hos/user/$ua/pwd"`ck"
fi
fi
if [ "${pa}ck" == "$np" ]
then
na="$ua"
usv="$hos/user/$na"
mpw="$usv/tmp"
else
$err
echo Join us?[Y/N]:
read ju
case $ju in
Y|y)
echo Please input your name:
read nep
echo Please input new password:
read npd
chk="`ls "$hos/user" | grep "$nep"`"
if [ "$chk" == "$nep" ]
then
$err
sleep 1
elif [ "$nep $npd" == " " ]
then
$err
sleep 1
else
echo Please input verifcation code:
vv="`cat /proc/sys/kernel/random/uuid | awk -F- '{printf("%s",$1)}'`"
echo $vv
read vc
if [ "$vc" == "$vv" ]
then
mkdir "$hos/user/$nep"
mkdir "$hos/user/$nep/diary"
echo $npd>>$hos/user/$nep/pwd
else
$err
sleep 1
fi
fi
;;
esac
fi
}
fid(){
while true
do
clear
cat "$rmk"
echo Press enter to back
if [ "$na" == "guest" ]
then
read nul
break 1
else
echo Input e to insert a new paragraph
echo Input c to continue write
read pd
case $pd in
e)
clear
echo Input title:
read tt
echo Word:
read nwd
echo >>$rmk
echo $tt >>$rmk
echo -------- >>$rmk
echo $nwd >>$rmk
;;
c)
echo Word:
read nw 
echo $nw >>$rmk
;;
*)
break 1
;;
esac
fi
done
}
zxth(){
while true
do
clear
cat "$wbb"
echo 'Input reply(Input e go back):'
read ry
if [ "$ry" == "e" ]
then
break 1
elif [ "$ry" == "" ]
then
echo refreshing... 
else
if [ "$na" == "guest" ]
then
wblg
else
echo $na  `date` >>$wbb
echo $ry >>$wbb
echo >>$wbb
fi
fi
done
}
pxcx(){
while read nr
do
co=$(($co+1))
if [ "$sel" -le "$co" -a "$(($sel+10))" -ge "$co" ]
then
echo $co.$nr
fi
done
}
na="guest"
mpw="$hos/tmp"
sleep 1
while true
do
clear
echo MaWiki  User:$na
echo Total entry:`ls "$whk" | wc -l`
echo ================
echo 1.Search
echo 2.Exit
echo 3.Go to MaBBS
echo 4.Random
if [ "$na" == "guest" ]
then
echo 5.Login
else
echo 5.Make a new entry
echo 6.Diary 
echo 7.Reset your password
fi
echo Input command:
read cmd
case $cmd in
1)
clear
echo Input Keyword or tags:
read kw
if [ "$kw" == "" ]
then
$err
sleep 1
else
clear
echo Result
echo =========
ls "$whk" | grep "$kw" | awk -F+ '{printf("%s\n",$1)}'
echo Which one:
read mtt
tkw=`ls "$whk" | grep "$mtt"`
if [ "$tkw" == "" ]
then
$err
sleep 1
else
if [ -e "$whk/$tkw" ]
then
rmk="$whk/$tkw"
fid
else
$err
fi
fi
fi
;;
2)
echo Bye
break
;;
3)
while true
do
clear
echo Welecome,$na
date
if [ -e "$hos/bul" ]
then
echo Bulletin:`cat "$hos/bul"`
fi
echo =============
co=0
ls "$hos/main" | while read bm
do
co=$(($co+1))
echo $co.$bm \(`ls "$hos/main/$bm/" | wc -l `\)
done
echo =============
echo a.Send massage
echo b.Open massage box 
echo c.Back to MaWiki
if [ "$na" == "SYSOP" ]
then
echo d.Make a part
echo e.Delete a part
echo f.Release bulletin
fi
echo Input number or command: 
read pac
if [ "$pac" == "" ]
then
pac="#"
fi
case $pac in
a)
clear
echo Which a user
echo ==============
ls "$hos/user"
echo AI
echo Send to:
read st
if [ "$st" == "" ]
then
$err
sleep 1
else
echo Word:
read swd
if [ "$st" == "AI" ]
then
if [ "$swd" == "study" ]
then
echo You say:
read ys
echo AI say:
read as
echo $ys-$as >>${hos}/ai
fi
ais="`cat "$hos/ai"|grep "$swd"|awk -F- '{printf("%s\n",$2)}'`"
if [ "$ais" == "" ]
then
ais="Sorry,I don't know what do you say."
fi
echo Talk AI say to you:$ais >>$hos/user/$na/tip
else
if [ -e "$hos/user/$st" ]
then
echo $na say to you:$swd >>$hos/user/$st/tip
echo OK!
else
$err
fi
sleep 1
fi
fi
;;
b)
clear
if [ -e "$usv/tip" ]
then
cat "$usv/tip"
else
echo Not found...
fi
echo Press enter to back
read nul
;;
c)
break
;;
d)
clear
if [ "$na" == "SYSOP" ]
then
echo New part name:
read npn
mkdir "$hos/main/$npn"
fi
;;
e)
if [ "$na" == "SYSOP" ]
then
echo Which part to delete:
read dpw
rm -rf "$hos/main/$dpw"
fi
;;
f)
if [ "$na" == "SYSOP" ]
then
clear
echo Input bulletin:
read bul
echo "$bul" > $hos/bul
fi
;;
*)
wbn=""
co="0" 
ls "$hos/main">$mpw
while read nr
do
co=$(($co+1))
if [ "$pac" == "$co" ]
then
wbn="$nr"
fi
done < $mpw
if [ "$wbn" == "" ]
then
$err
else
pac="$wbn"
sel="0"
while true
do
pcz="$hos/main/$pac"
clear
echo Welecome,$na   Part:$pac
echo =============
co="0"
ls "$pcz" | pxcx
echo =============
echo a.Make a new post
echo b.Back
if [ `ls "$pcz" | wc -l ` -ge 10 ]
then
echo c.Next page
fi
if [ "$na" == "SYSOP" ]
then 
echo d.Delete a post
fi
echo Input number or command:
read int
case $int in
a)
if [ "$na" == "guest" ]
then
wblg
else
clear
echo 'This is a [1.Post 2.Vote]:'
read cht
case $cht in
1)
clear
echo Input the title:
read tit
if [ "`ls "$pcz" | grep "$tit"`" == "" ]
then
echo Word:
read wod
stt="$pcz/$tit"
echo $tit >>$stt
echo ============= >>$stt
echo Post master:$na  `date` >>$stt
echo $wod >>$stt
echo >>$stt
fi
;;
2)
clear
echo Input the title:
read tit
if [ "`ls "$pcz" | grep "$tit"`" == "" ]
then
echo Main word:
read wod
echo "Option head:"
read oph
echo "Option:"
read opt
echo 'Use talking?[Y/N]:'
read utk
tsm="$pcz/$tit"
mkdir "$tsm"
echo $tit >>$tsm/main
echo ============= >>$tsm/main
echo Vote master:$na  `date` >>$tsm/main
echo $wod >>$tsm/main
echo $opt>>$tsm/data
mkdir "$tsm/opt" 
for sle in $oph
do
touch "$tsm/opt/$sle"
done
if [ "$utk" == "y" ]
then
echo Talk>>"$tsm/talk"
echo ========= >>"$tsm/talk"
fi
fi
;; 
esac
fi
;;
b)
break 1
;;
c)
if [ `ls "$pcz" | wc -l ` -ge 10 ] 
then
sel="$(($sel+10))"
fi
;;
d)
if [ "$na" == "SYSOP" ]
then 
echo Which post delete:
read tdw
rm -rf "$pcz/$tdw"
fi
;; 
*)
wbn=""
co="0"
ls "$pcz" > $mpw
while read nr
do
co=$(($co+1))
if [ "$int" == "$co" ]
then
wbn="$nr"
fi
done < $mpw
if [ "$wbn" == "" ]
then
$err
else
wbb="$pcz/$wbn"
if [ -f "$wbb" ]
then
zxth
else
chse(){
if [ "$na" == "guest" ]
then
wblg
else
vck="`cat "${ifw}opt/$1" | grep "$na"`"
if [ "$na" == "$vck" ]
then
$err
sleep 1
else
echo $na >> "${ifw}opt/$1"
clear
cat "${ifw}opt/$1"
echo selected it.
sleep 3
fi
fi
}
ifw="${wbb}/"
clear
cat "${ifw}main"
echo ==========
cc(){
for lop in `ls "${ifw}opt/"`
do
echo $lop.$1 \(`cat "${ifw}opt/$lop" | wc -l`\)
shift
done
}
cc `cat "${ifw}data"`
if [ -e "${ifw}talk" ]
then
echo Input t to talk,or
fi
echo 'Choose one:'
read ry
if [ "$ry" == "" ]
then
$err
else
if [ "$ry" == "t" ]
then
if [ -e "${ifw}talk" ]
then
wbb="${ifw}talk"
zxth
fi
else
if [ -e "${ifw}opt/$ry" ]
then
chse $ry
fi
fi
fi
fi
fi
;;
esac
done
fi
;;
esac
done 
;;
5)
if [ "$na" == "guest" ]
then
wblg
else
clear
echo Input Main title:
read mt
if [ "`ls "$whk" | grep "$mt"`" == "" ]
then
echo Tags:
read tgs
echo Word:
read wd
mwt="$whk/$mt+$tgs"
echo $mt>>$mwt
echo Made by:$na `date`>>$mwt
echo Tags:$tgs>>$mwt
echo ========= >>$mwt
echo $wd >>$mwt
rmk="$whk/$mt+$tgs"
fid
fi
fi
;;
4)
jld="`ls "$whk" | wc -l`"
if [ "$jld" == "0" ]
then
echo Not found...
sleep 1
else
num=`date +%s`
ranm=$(($num%$jld+1))
co="0"
ls "$whk" > $mpw
while read nr
do
co="$(($co+1))"
if [ "$co" == "$ranm" ]
then
rmk="$whk/$nr"
fi
done < $mpw
fid
fi
;;
6)
if [ "$na" == "guest" ] 
then
wblg
else
cfd="$usv/diary"
sel="0"
while true
do
clear
echo Welecome,$na
echo =============
co="0"
ls "$cfd" | pxcx
echo =============
echo a.Write diary
echo b.Back
if [ `ls "$cfd" | wc -l ` -ge 10 ]
then
echo c.Next page
fi
echo Input number or command:
read int
case $int in
a)
clear
mt="`date +%y.%m.%d`"
if [ "`ls "$cfd" | grep "$mt"`" == "" ]
then
echo Word:
read wd
mwt="$cfd/$mt"
echo Diary:$mt>>$mwt
echo $wd >>$mwt
fi
rmk="$cfd/$mt"
fid
;;
b)
break 1
;;
c)
if [ `ls "$cfd" | wc -l ` -ge 10 ] 
then
sel="$(($sel+10))"
fi 
;;
*)
rmk=""
co="0"
ls "$cfd" > $mpw
while read nr
do
co="$(($co+1))"
if [ "$co" == "$int" ]
then
rmk="$cfd/$nr"
fi
done < $mpw
if [ -e "$rmk" ]
then
fid
fi
;;
esac
done
fi
;;
7)
if [ "$na" == "guest" ] 
then
wblg
else 
clear
echo Input your new password:
read nrd
if [ "$nrd" == "" ]
then
$err
sleep 1
else
echo $nrd>$usv/pwd
fi
fi
;;
*)
$err
sleep 1
;;
esac
done